name: CI DevSecOps

on: [push, pull_request]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1

    - name: Run OWASP Dependency Check
      run: |
        docker run --rm \
          -v "$(pwd):/src" \
          owasp/dependency-check \
          --scan /src \
          --format ALL \
          --project "devsecops-tp"
